# New "AI-human collaboration" section (todo/034 #5, D-12), 2026-06-27
#
# DECISION (Marcus, AskUserQuestion): (a) SPLIT -- a new early section between the
# Introduction and the Background takes the narrative/novelty framing (AI-human
# collaboration is a novelty in the age of AI; a stated goal is a workflow that is
# both productive AND yields accurate conclusions) plus the roles material, while
# Methods keeps the operational verification detail. (b) Insert as internal id S1B
# (anchor sec-ai-collab); do NOT renumber S2 onward (reader-facing numbers are
# auto-generated by Quarto from order).
#
# Touches all four plan JSONs + decisions.md. Run once.

import json

BASE = r"C:\Users\marcu\git-repositories\mi-spectral\manuscript\plan"
L1 = BASE + r"\level1-thesis.json"
L2 = BASE + r"\level2-sections.json"
L3 = BASE + r"\level3-paragraphs.json"
L4 = BASE + r"\level4-evidence.json"
DEC = BASE + r"\decisions.md"
TITLE = "AI–human collaboration"

def load(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)
def save(p, d):
    with open(p, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
        f.write("\n")

# ======================================================================= LEVEL 3
l3 = load(L3)

# -- sections_order: insert S1B right after S1 ----------------------------------
so = l3["sections_order"]
ids = [s["id"] for s in so]
assert "S1B" not in ids, "S1B already present"
i_s1 = ids.index("S1")
so.insert(i_s1 + 1, {"id": "S1B", "anchor": "sec-ai-collab", "title": TITLE})

paras = l3["paragraphs"]
by = {p["id"]: p for p in paras}

# -- new framing paragraph S1B-P1 -----------------------------------------------
S1B_P1_PROSE = (
    "This paper is also a demonstration of a way of working. The derivations were "
    "produced through a collaboration between a human author and an AI system. "
    "Collaboration of this kind is new in the age of AI, and its products are not "
    "yet routinely trusted. One stated goal of this paper is therefore to show a "
    "workflow that is at once productive and accurate. Productive means that the "
    "collaboration reached results a single author would have reached slowly or not "
    "at all. Accurate means that those results hold up to the scrutiny a skeptical "
    "referee applies to human-derived mathematics. The division of labor is simple "
    "to state. The human author set the direction, fixed the standards, supplied "
    "field knowledge, and accepted or rejected each result. The AI system produced "
    "the derivations, the drafts, and the computations. The provenance is "
    "transparent by design. The human prompter of record is ORCID-verified, and the "
    "full record of the work is public. This section describes the collaboration "
    "and shows that it was productive. @sec-methods states the verification protocol "
    "that makes its conclusions accurate, and what each safeguard cannot catch."
)
S1B_P1 = {
    "id": "S1B-P1",
    "section": "S1B",
    "goal": "position_lineage",
    "proposition": ("AI-human collaboration is a novelty in the age of AI, and a "
        "stated goal of this paper is to demonstrate a workflow that is both "
        "productive and yields accurate conclusions; the division of labor (human "
        "direction, standards, field knowledge and acceptance; AI derivations, "
        "drafts and computations) and the transparent ORCID-verified provenance are "
        "stated here, with the accuracy safeguards deferred to @sec-methods."),
    "depends_on": ["S1-P7"],
    "dep_types": ["builds_on"],
    "review": {
        "serves_L2": "S1B-SP1",
        "serves_L1": "M1b AI-HUMAN COLLABORATION (methodological thesis; novelty + productive-and-accurate goal; D-12)",
        "sets_up": "S1B-P2 (the measured collaboration); @sec-methods",
        "topic_sentence": "This paper is also a demonstration of a way of working.",
        "closing_sentence": "@sec-methods states the verification protocol that makes its conclusions accurate, and what each safeguard cannot catch.",
        "status": "drafted",
        "flags": "ai-collab-restructure 2026-06-27 (todo/034 #5): new section framing paragraph.",
    },
    "audit": {
        "status": "complete",
        "citations": {},
        "numbers": {},
        "notes": ("Rhetorical/framing paragraph; cross-references only (@sec-methods "
            "hand-off). States the AI-era novelty and the productive-and-accurate "
            "workflow goal (todo/034 #5, D-12). T-03 vocabulary check passed."),
    },
    "draft_prose": S1B_P1_PROSE,
}

# -- relocate S3-P2 -> S1B-P2 (roles, measured collaboration) -------------------
p2 = by["S3-P2"]
assert p2["draft_prose"].count("The remaining parts exist for that.") == 1
p2["draft_prose"] = p2["draft_prose"].replace(
    "The remaining parts exist for that.",
    "The verification protocol of @sec-methods exists for that.")
p2["id"] = "S1B-P2"
p2["section"] = "S1B"
p2["depends_on"] = ["S1B-P1"]
p2["dep_types"] = ["builds_on"]
p2["review"]["serves_L2"] = "S1B-SP2"
p2["review"]["serves_L1"] = "M1b AI-HUMAN COLLABORATION (methodological thesis; measured collaboration; D-12)"
p2["review"]["sets_up"] = "@sec-methods (the verification protocol)"
p2["review"]["flags"] = "ai-collab-restructure 2026-06-27 (todo/034 #5): relocated from Methods opener (old S3-P2)."
p2["audit"]["notes"] = p2["audit"]["notes"] + " Relocated 2026-06-27 from S3 (Methods) to S1B (AI-human collaboration) per todo/034 #5 / D-12; closing sentence now hands off to @sec-methods."

# -- rebuild paragraph list: drop old S3-P2 object, insert S1B-P1 + S1B-P2 after S1-P7
paras = [p for p in paras if p["id"] != "S1B-P2"]   # remove the relocated obj (now id S1B-P2)
out = []
for p in paras:
    out.append(p)
    if p["id"] == "S1-P7":
        out.append(S1B_P1)
        out.append(p2)
l3["paragraphs"] = out
by = {p["id"]: p for p in out}

# -- re-point Methods deps that pointed at the moved paragraph -------------------
for pid in ("S3-P3", "S3-P4"):
    p = by[pid]
    assert p["depends_on"] == ["S3-P2"], "%s depends_on changed: %s" % (pid, p["depends_on"])
    p["depends_on"] = ["S3-P1"]

# -- edit S1-P7 (Intro meta paragraph): hand off to the new section -------------
S1P7_NEW = (
    "One feature of this paper bears on how it should be read, and the title page "
    "declares it. The derivations are AI-assisted, with an ORCID-verified human "
    "prompter of record. @sec-ai-collab describes the collaboration that produced "
    "them and shows that it was productive. @sec-methods states the verification "
    "protocol under which every claim was produced and checked, and what each "
    "safeguard can and cannot catch. The results are then offered to be judged "
    "through that protocol, the way an empirical paper's results are judged through "
    "its methods. The rest of the paper proceeds as follows. @sec-background fixes "
    "notation and restates the standard results at the precision the argument "
    "needs. @sec-derivations develops the theorem and both applications. "
    "@sec-simulations reports the pre-registered studies, including the predictions "
    "that failed. @sec-discussion states what is firm, what is measured, and what "
    "is conjectured."
)
by["S1-P7"]["draft_prose"] = S1P7_NEW
by["S1-P7"]["review"]["sets_up"] = "S1B (AI-human collaboration), S3 (Methods), section sequence"

# -- edit S3-P1 (Methods opener): five parts, points back to @sec-ai-collab -----
S3P1_NEW = (
    "The collaboration that produced these derivations is described in "
    "@sec-ai-collab. This section states the verification protocol under which the "
    "results were produced and checked. The protocol answers one question. Why do "
    "the results that follow deserve the same scrutiny that is applied to "
    "human-derived mathematics? The protocol has five parts. The first is sourced "
    "citations. The second is a verification pipeline with explicit trust tiers. "
    "The third is preregistration of every simulation. The fourth is adversarial "
    "cross-model review. The fifth is full reproducibility. Each part is stated "
    "below together with what it can catch and what it cannot. The complete "
    "protocol records are collected in the appendices and the public repository. "
    "These records include the decision logs, the grading sheets, the amendment "
    "histories, and the enforcement code. This section states the design."
)
by["S3-P1"]["draft_prose"] = S3P1_NEW
by["S3-P1"]["review"]["topic_sentence"] = "The collaboration that produced these derivations is described in @sec-ai-collab."
by["S3-P1"]["review"]["sets_up"] = "all S3 verification paragraphs; S4/S5 tier usage"

l3["metrics_gate"]["notes"] = (
    "AI-human collaboration section added 2026-06-27 (todo/034 #5, D-12): new S1B "
    "(sec-ai-collab) inserted between S1 and S2 with S1B-P1 (framing: AI-era novelty "
    "+ productive-and-accurate goal) and S1B-P2 (roles, relocated from S3-P2); S1-P7 "
    "and S3-P1 rewritten to hand off (Methods now five parts); S3-P3/S3-P4 deps "
    "re-pointed to S3-P1. Prior note: " + (l3["metrics_gate"].get("notes") or ""))

save(L3, l3)

# ======================================================================= LEVEL 2
l2 = load(L2)
secs = l2["sections"]
sids = [s["id"] for s in secs]
assert "S1B" not in sids

# move S3-SP1 (roles) out of S3
s3 = next(s for s in secs if s["id"] == "S3")
roles_sp = next(sp for sp in s3["super_propositions"] if sp["id"] == "S3-SP1")
s3["super_propositions"] = [sp for sp in s3["super_propositions"] if sp["id"] != "S3-SP1"]
s3["depends_on"] = ["S1B"]
s3["goal_statement"] = (
    "State the verification protocol as method - factually, in the passive voice "
    "(T-05), one paragraph per part, each gate paragraph ending with what that gate "
    "cannot catch - so that 'why believe an AI derivation' is answered as procedure "
    "before any result is asked to be believed. The collaboration and roles are "
    "described in the preceding AI-human collaboration section (S1B); this section "
    "covers the five verification parts (sourced citations, the claim pipeline with "
    "trust tiers, preregistration, cross-model adversarial review, reproducibility). "
    "The fitted-versus-true-model sign episode is the single narrative passage. "
    "Defers: protocol records to appendices, proofs to the companion document, "
    "results to S4/S5. Serves the methodological thesis component. Sits deliberately "
    "low on the technical gradient (not announced in the text)."
)

# give the relocated roles SP a stable new id + the collaboration-analysis pointer
roles_sp["id"] = "S1B-SP2"
if "verif:verification/collaboration-analysis.md" not in roles_sp["evidence"]:
    roles_sp["evidence"] = ["verif:verification/collaboration-analysis.md"] + roles_sp["evidence"]

S1B_SECTION = {
    "id": "S1B",
    "arc_move": "M1b_AI_COLLABORATION",
    "anchor": "sec-ai-collab",
    "title": TITLE,
    "mapping_from_180e2b5": ("NEW section (todo/034 #5, D-12). Pulls the AI-human "
        "collaboration framing forward from the Introduction's meta paragraph (S1-P7) "
        "and relocates the roles material from the Methods opener (old S3-P2 / "
        "S3-SP1). Methods keeps the operational verification detail."),
    "goal_statement": ("Foreground the AI-human collaboration as a contribution in "
        "its own right, between the Introduction and the Background: state that "
        "collaboration of this kind is a novelty in the age of AI and that a stated "
        "goal of the paper is a workflow that is both productive AND yields accurate "
        "conclusions, give the division of labor and the transparent ORCID-verified "
        "provenance, and show the collaboration was productive from the coded session "
        "record - then hand off to Methods for the safeguards that secure accuracy. "
        "Defers all verification detail to S3. Serves the methodological thesis "
        "component. Sits low on the technical gradient. Style: plain expository, "
        "trust-ordered, no banned vocabulary (T-03)."),
    "estimated_paragraphs": "2-3",
    "super_propositions": [
        {
            "id": "S1B-SP1",
            "claim": ("AI-human collaboration is a novelty in the age of AI, and a "
                "stated goal of the paper is a workflow that is both productive (it "
                "reaches results a single author would have reached slowly or not at "
                "all) and accurate (the results withstand the scrutiny a skeptical "
                "referee applies to human-derived mathematics): the human sets "
                "direction, standards, field knowledge and acceptance, the AI "
                "produces the derivations, drafts and computations, and provenance is "
                "transparent and ORCID-verified."),
            "goal": "position_lineage",
            "evidence": ["deriv:sec-verify", "verif:manuscript/plan/decisions.md"],
            "evidence_status": "grounded",
        },
        roles_sp,  # relocated S3-SP1 -> S1B-SP2 (roles and decision discipline, measured)
    ],
    "depends_on": ["S1"],
    "dep_types": ["builds_on"],
    "feeds_forward_to": ["S2", "S3", "S4", "S5", "S6"],
}

# insert S1B section right after S1; update S1 feeds_forward
i_s1 = sids.index("S1")
secs.insert(i_s1 + 1, S1B_SECTION)
s1 = next(s for s in secs if s["id"] == "S1")
if "S1B" not in s1["feeds_forward_to"]:
    s1["feeds_forward_to"] = ["S1B"] + s1["feeds_forward_to"]

# dependency_graph
l2["dependency_graph"]["S1B"] = ["S1"]
l2["dependency_graph"]["S3"] = ["S1B"]

l2["metrics_gate"]["notes"] = (
    "AI-human collaboration section S1B inserted 2026-06-27 (todo/034 #5, D-12): "
    "roles super-proposition relocated from S3 (now S1B-SP2) plus a new framing SP "
    "(S1B-SP1); S3 drops to five verification parts and now depends_on S1B; DAG "
    "re-checked acyclic. Prior note: " + (l2["metrics_gate"].get("notes") or ""))

save(L2, l2)

# ======================================================================= LEVEL 1
l1 = load(L1)
arc = l1["persuasion_arc"]
arc["total_moves"] = 7
arc["design_note"] = ("IMRaD adapted to an AI-human derivation (D-09; D-12 adds the "
    "AI-human collaboration move): Introduction / AI-human collaboration / Background "
    "/ Methods-as-workflow / Derivations / Simulation studies / Discussion. M1b "
    "foregrounds the collaboration (novelty + the productive-and-accurate goal + "
    "roles) between M1 and M2; the operational verification protocol stays in M3. "
    "The Results umbrella of the original D-09 is split into M4a Derivations and M4b "
    "Simulation studies; within Derivations the internal order stays theorem -> LRT "
    "-> IC (D-03). Technical-gradient design: M2 ramps the reader up, M1b and M3 sit "
    "low (process, not mathematics), M4a is the peak, M4b steps back down, M5 "
    "descends to the M1 reader (no announcement of this in the text).")

moves = arc["moves"]
m1 = next(m for m in moves if m["id"] == "M1")
old4 = "(4) Final paragraph, meta layer: this is an AI-human derivation under a stated verification protocol, reported in full as the Methods section; one paragraph, no more."
assert m1["function"].count(old4) == 1
m1["function"] = m1["function"].replace(old4,
    "(4) Final paragraph, meta layer: this is an AI-human derivation, with the "
    "collaboration described in the AI-human collaboration section that immediately "
    "follows (M1b) and the verification protocol reported in full as Methods; one "
    "paragraph, no more.")
for i, kc in enumerate(m1["key_claims"]):
    if kc.startswith("The derivation is AI-assisted under a stated verification protocol"):
        m1["key_claims"][i] = ("The derivation is AI-assisted; the collaboration is "
            "foregrounded in its own section (M1b) and the verification protocol "
            "reported as Methods - final paragraph only")

M1B_MOVE = {
    "id": "M1b",
    "label": "AI-HUMAN COLLABORATION",
    "section_anchor": "sec-ai-collab",
    "title": TITLE,
    "function": ("Foreground the AI-human collaboration as its own section between "
        "the Introduction and the Background (todo/034 #5, D-12). Two short "
        "paragraphs. (1) Framing: collaboration between a human author and an AI "
        "system is a novelty in the age of AI, and a stated goal of this paper is to "
        "demonstrate a workflow that is at once productive (it reaches results a "
        "single author would have reached slowly or not at all) and accurate (those "
        "results withstand the scrutiny a skeptical referee applies to human-derived "
        "mathematics); the division of labor is stated plainly (human direction, "
        "standards, field knowledge and acceptance; AI derivations, drafts and "
        "computations) and provenance is transparent and ORCID-verified; the framing "
        "hands off to Methods for the safeguards that secure accuracy. (2) The "
        "measured collaboration: the roles material relocated from the old Methods "
        "opener, the five collaboration patterns coded from the committed session "
        "record, closing on the limit that recording who decided what certifies "
        "nothing about correctness, which is the verification protocol's job. STYLE: "
        "plain expository, no banned vocabulary (T-03), trust-ordered; sits low on "
        "the technical gradient (process, not mathematics)."),
    "serves_thesis": ["methodological"],
    "key_claims": [
        "AI-human collaboration is a novelty in the age of AI; a stated goal of the paper is a workflow that is both productive and yields accurate conclusions",
        "Division of labor stated plainly: human sets direction, standards, field knowledge and acceptance; AI produces derivations, drafts and computations; provenance transparent and ORCID-verified",
        "The collaboration is measured, not recalled: five patterns coded from the committed session record",
        "Productivity is shown here; accuracy is secured by the verification protocol stated as Methods (the split)",
    ],
    "evidence_base": [
        "deriv:sec-verify",
        "verif:verification/collaboration-analysis.md",
        "verif:manuscript/plan/decisions.md",
    ],
    "rhetorical_role": ("The reader meets the paper's methodological novelty up front "
        "- what the collaboration is and that it was productive - before the "
        "Background, with the accuracy case deferred to Methods where it is argued as "
        "procedure."),
}
i_m1 = [m["id"] for m in moves].index("M1")
moves.insert(i_m1 + 1, M1B_MOVE)

# M3 function: five parts, roles moved out
m3 = next(m for m in moves if m["id"] == "M3")
m3["function"] = ("State the verification protocol as method, in five parts, one "
    "tight paragraph each (roles and the collaboration are covered in the preceding "
    "AI-human collaboration section, M1b): (1) sourced derivation - every external "
    "claim pinned to a source passage in a locally archived session-read copy, "
    "citation discipline enforced mechanically by a pre-write hook; (2) claim "
    "pipeline - derive, then symbolic verification in two independent computer-"
    "algebra systems, then Monte Carlo confirmation, with trust tiers (firm / "
    "measured / structural / conjecture) assigned by the gates cleared; (3) "
    "preregistration before code - predictions and pass criteria frozen and "
    "committed first, dated amendments, failures reported; (4) cross-model "
    "adversarial verification - blind re-derivation by an independent model lineage "
    "plus an instructed-to-refute pass, grading records committed, with the fitted-"
    "versus-true-model sign episode as the single narrative passage; (5) "
    "reproducibility - seeds, caches, single-entrypoint scripts, environment "
    "records. STYLE (T-05): written factually in the passive voice - the protocol is "
    "described as a procedure, not narrated as an achievement. STRUCTURAL "
    "REQUIREMENT: every gate paragraph ends with what that gate cannot catch. "
    "LENGTH: full protocol records (grading records, amendment logs, hook mechanics, "
    "per-gate specifications) go to appendices (single submission document; repo "
    "cited for the full audit trail) - recorded as a D-08 note. Drafting guidance "
    "(not announced in the text): M3 sits lower on the technical gradient than "
    "M2/M4a; keep it that way.")

l1["decisions"].append({
    "id": "D-12",
    "date": "2026-06-27",
    "label": "Foreground AI-human collaboration as its own section (between Introduction and Background)",
    "chosen": ("A new section 'AI-human collaboration' (anchor sec-ai-collab, "
        "internal id S1B, arc move M1b) is inserted between the Introduction and the "
        "Background. It takes the narrative and novelty framing - that AI-human "
        "collaboration is a novelty in the age of AI and that a stated goal of the "
        "paper is a workflow that is both productive AND yields accurate conclusions "
        "- plus the roles material relocated from the Methods opener (old S3-P2). "
        "Methods (S3/M3) keeps the operational verification detail and drops from "
        "six parts to five (roles moved out). Internal section ids S2-S6 and all "
        "paragraph ids are left unchanged; reader-facing section numbers are "
        "auto-generated by Quarto from order."),
    "rejected_options": {
        "move_all_workflow_forward": ("Moving the entire workflow treatment "
            "(citation discipline, verification gates, CAS/cross-model checks) into "
            "the new early section would leave Methods thin or redundant and would "
            "put operational procedure before the Background the reader needs - "
            "rejected (Marcus, todo/034 #5)."),
        "renumber_sections": ("Renumbering S2 onward (new section as S2, Background "
            "S3, and so on) would churn every section key, paragraph id prefix, and "
            "depends_on link across the plan scaffold for no reader-facing change, "
            "since Quarto numbers sections from order regardless - rejected in favor "
            "of inserting as S1B with stable ids."),
    },
    "provenance": "Marcus in-chat, todo/034 #5, 2026-06-27 (AskUserQuestion: split + S1B/no-renumber)",
    "status": "ratified",
})

l1["metrics_gate"]["arc_moves"] = 7
l1["metrics_gate"]["notes"] = (
    "Seven moves after D-12 (M1b AI-human collaboration inserted between M1 and M2). "
    + (l1["metrics_gate"].get("notes") or ""))

save(L1, l1)

# ======================================================================= LEVEL 4
l4 = load(L4)
renamed = 0
for e in l4.get("evidence_map") or []:
    if e.get("proposition_id") == "S3-P2":
        e["proposition_id"] = "S1B-P2"
        renamed += 1
save(L4, l4)

# ======================================================================= decisions.md
entry = (
    "\n## New \"AI-human collaboration\" section (2026-06-27, todo/034 #5, D-12)\n\n"
    "A new section titled \"AI-human collaboration\" (anchor sec-ai-collab, internal "
    "id S1B, arc move M1b) is inserted between the Introduction and the Background. "
    "Decision by Marcus (AskUserQuestion): SPLIT -- the new early section takes the "
    "narrative/novelty framing (AI-human collaboration is a novelty in the age of "
    "AI; a stated goal of the paper is a workflow that is both productive AND yields "
    "accurate conclusions) plus the roles material relocated from the Methods opener "
    "(old S3-P2), while Methods keeps the operational verification detail and drops "
    "from six parts to five. Inserted as S1B with NO renumbering of S2 onward; "
    "reader-facing section numbers are auto-generated by Quarto from order. Scaffold: "
    "S1B-P1 (new framing) + S1B-P2 (relocated roles) in level3; S1B blueprint with "
    "S1B-SP1 (framing) + S1B-SP2 (relocated roles SP) in level2; M1b move + this "
    "D-12 in level1; level4 proposition_id S3-P2 -> S1B-P2. S1-P7 and S3-P1 "
    "rewritten to hand off; S3-P3/S3-P4 deps re-pointed to S3-P1.\n"
)
with open(DEC, "a", encoding="utf-8") as f:
    f.write(entry)

print("AI-collab restructure applied.")
print("  level4 proposition_id renames S3-P2 -> S1B-P2:", renamed)
